### ISSUE TITLE
Pembuatan Mockup

### ISSUE THREAD

**Issue by fighaz** [fighaz/puhsepuh_inventory_2d#1]

**Comment by abdaziz-04** [comment]
https://www.figma.com/file/cY3pYZ7e70knINDZqZFAOn/Desain?type=design&node-id=0-1&mode=design&t=WWoY4roEU0eKWc4m-0

**Comment by abdaziz-04** [comment]
https://www.figma.com/file/cY3pYZ7e70knINDZqZFAOn/Desain?type=design&node-id=1%3A13&mode=design&t=Vs0H28XTmvZk0IL1-1
