### ISSUE TITLE
Desain page list inventaris

### ISSUE THREAD

**Issue by abdaziz-04** [fighaz/puhsepuh_inventory_2d#16]

**Comment by Febilid** [comment]
mock-up : https://www.figma.com/proto/cY3pYZ7e70knINDZqZFAOn/Inventaris-JTI?type=design&node-id=288-133&t=LMW6qEuI4X7R94cd-0&scaling=scale-down&page-id=1%3A13&starting-point-node-id=85%3A4&show-proto-sidebar=1

link : https://www.figma.com/file/cY3pYZ7e70knINDZqZFAOn/Inventaris-JTI?type=design&node-id=288-133&mode=design&t=LMW6qEuI4X7R94cd-0
